feat: :sparkles: Implement debouncing for search input in DataTableHe…
eDonec/boilerplate pull request #99
Opened 2024-01-12 09:49 UTC by meleklassoued

### Description:
Add a debouncing mechanism to the search input field (RawInput) within the DataTableHeader component to optimize performance. This enhancement reduces the frequency of calls to the onKeywordChange handler, improving the overall user experience during typing.

### Fixes: #98

2024-01-12 11:27 UTC, nader-zouaoui commented on packages/browser/core-hooks/useDebounce/index.ts
> +const DEFAULT_DELAY = 500;
reduce delay to 200

2024-01-12 11:28 UTC, nader-zouaoui commented on packages/browser/core-hooks/useDebounce/index.ts
> +  };
This function is not needed as it offers no additional functionality to the orignal setState

2024-01-12 11:31 UTC, nader-zouaoui commented on packages/browser/core-hooks/useDebounce/index.ts
> +      if (debouncedValue !== undefined) {
Why did you add this?
what if I want to clear the input what happens then?

2024-01-12 11:33 UTC, nader-zouaoui commented on packages/browser/core-hooks/useDebounce/index.ts
> +  }, [debouncedValue, delay, debounceResolutionCallback]);
Remove `debounceResolutionCallback` it could cause an infinite loop

2024-01-12 11:34 UTC, nader-zouaoui commented on packages/browser/data-table/InternalUncontrolledDataTable/hooks/useUncontrolledDataTable.ts
> +  const handleKeywordDebounced = (tempKeyword: string) => {
Rename `tempKeyword` to something more meaningful (like `debouncedKeyword`)

2024-01-12 11:35 UTC, nader-zouaoui commented on packages/browser/data-table/InternalUncontrolledDataTable/hooks/useUncontrolledDataTable.ts
> +  const onKeywordChange = (tempKeyword: string) => {
Rename `tempKeyword` to something more meaningful (like `inputKeyword` or `newKeyword` or something better)

2024-01-12 14:33 UTC, nader-zouaoui requested changes

2024-01-12 14:33 UTC, nader-zouaoui commented on packages/browser/data-table/InternalUncontrolledDataTable/hooks/useUncontrolledDataTable.ts
> +  const onKeywordChange = (newKeyWord: string) => {
`Keyword` is one word and does not need the upper case `w`

2024-01-12 14:33 UTC, nader-zouaoui commented on packages/browser/data-table/InternalUncontrolledDataTable/hooks/useUncontrolledDataTable.ts
> +  const debounceValue = useDebounce(handleKeywordDebounced);
`debounceValue` can be changed to a better name (what value are we talking about)

2024-01-12 14:33 UTC, nader-zouaoui commented on packages/browser/data-table/InternalUncontrolledDataTable/hooks/useUncontrolledDataTable.ts
> +  const handleKeywordDebounced = (debouncedKeyword: string) => {
this function name can also be improved

2024-01-22 10:03 UTC, meleklassoued reviewed
Improve clarity and naming in keyword handling functions

2024-01-30 16:14 UTC, nader-zouaoui requested changes

2024-02-01 20:49 UTC, nader-zouaoui approved these changes

2024-02-01 20:49 UTC, merged